// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// ignore: unnecessary_import
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWzggDvRMUjVxw-ufJY1SIwCanEgIiec',
    appId: '1:883279851370:android:d5a36336d438b0b81ebf13',
    messagingSenderId: '883279851370',
    projectId: 'myecommerceapp-be219',
    storageBucket: 'myecommerceapp-be219.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZVxZ5QaCrciTSzsxk0cfqV82-iX6bk8o',
    appId: '1:883279851370:web:8ff368464e5f23e21ebf13',
    messagingSenderId: '883279851370',
    projectId: 'myecommerceapp-be219',
    authDomain: 'myecommerceapp-be219.firebaseapp.com',
    storageBucket: 'myecommerceapp-be219.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZVxZ5QaCrciTSzsxk0cfqV82-iX6bk8o',
    appId: '1:883279851370:web:8ff368464e5f23e21ebf13',
    messagingSenderId: '883279851370',
    projectId: 'myecommerceapp-be219',
    authDomain: 'myecommerceapp-be219.firebaseapp.com',
    storageBucket: 'myecommerceapp-be219.firebasestorage.app',
  );
}
